language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: F8Igo2zSIROT6gEKmCA2ywFaM7adI2QiXvkM1l/Upreh4Zl3Ha2787FzF2I3xSIAM1NjuSipQ39DKX/F+TeBgOQshk3JHosPTakzRY+Ve6ldTIVJgn4QVy5QxUODrv8Ce+JpQLEnmVIwKFBA9AecYPS0aaRRQptTJtMXNQiGncU39Xr5cYIPDH2/vJBuH6zk//g0uc8tEpePU3DB27kNxFAYUyHRFkEiTwccd0b3zpCQaolVUNQ42j1EytisDTSAZbMIyy9VnyMd/fdMx4FLCLSbsVLQI+GewKjX9BAFa3WFTz05Q6Y6rwrKlD58P3CkRkDs+ZkTG1jbshILicsAzFd4Ie3NK2QIyC2Za71HoH4Pbtygpj7GtT7Syb/jFU5ANpLXY6yCeSgdFc/d4zI0OHFNoVc/ZI7lGEED+9JKWA24Ne3aD+z0vJH2uAbU4itnuoj5KBPbub35eFB9bipD0QpECbyr+VEZStqr93LaQsiiGktnCTES9gL3I7i56bZbHkjoWue9/V763Wzs2iEya6ITeN0EXUWkY+mOvAGVa0R/NMobA/hzTUuTsp4CE1OhpC44VW3werAI+Yc0xfpovAhQ2jNimCsn14pqwWQvXx432i92UpWMzE6I8mCs/SugReBcEPNx0I00NMxR88ONr6r12FOJ62kgRwQ7Vii2aTY=
  on:
    tags: true
    branch: master
    repo: DEGJS/formValidation-minMaxLength
